// <auto-generated />
using E_Commerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_Commerce.Migrations
{
    [DbContext(typeof(ECommDbContext))]
    [Migration("20190722180918_UpdateItemstoProducts")]
    partial class UpdateItemstoProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E_Commerce.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("Sku");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Stick on full beard. Glue not included",
                            Image = "http://placebeard.it/g/100/125",
                            Name = "Full Beard",
                            Price = 10.00m,
                            Sku = "001Bear"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Stick on soul patch. Glue not included",
                            Image = "http://placebeard.it/g/100/125",
                            Name = "Soul Patch",
                            Price = 2.00m,
                            Sku = "003Soul"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Full beard with hooks to hang off of ears.",
                            Image = "http://placebeard.it/g/100/125",
                            Name = "Old School Hook Beard",
                            Price = 10.00m,
                            Sku = "004Hook"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Long Fu-Man-Chu stick on mustache. Glue not included.",
                            Image = "http://placebeard.it/g/100/125",
                            Name = "Long Fu-Man-Chu Mustache",
                            Price = 8.00m,
                            Sku = "005Fu"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Short Fu-Man-Chu stick on mustache. Glue not included",
                            Image = "http://placebeard.it/g/100/125",
                            Name = "Short Fu-Man-Chu Mustache",
                            Price = 5.00m,
                            Sku = "006FuS"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Spray that allows for realistic looking 5'oclock shadow. Alcohol soluble.",
                            Image = "http://placebeard.it/g/100/125",
                            Name = "5'oclock Shadow Spray",
                            Price = 15.00m,
                            Sku = "007Shadow"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Glue for all stick on facial hair. Alcohol soluble.",
                            Image = "http://placebeard.it/g/100/125",
                            Name = "Facial Glue",
                            Price = 5.00m,
                            Sku = "008Glue"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Specially designed comb for facial hair.",
                            Image = "http://placebeard.it/g/100/125",
                            Name = "Facial Hair Comb",
                            Price = 5.00m,
                            Sku = "009Comb"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Stick on mutton chops. Glue not included",
                            Image = "http://placebeard.it/g/100/125",
                            Name = "Mutton Chops",
                            Price = 7.00m,
                            Sku = "010Chops"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
